export const products = [
  {
    id: "1",
    name: "Polarized UV Protection Sunglasses - Navy Blue",
    description: "Stylish navy blue sunglasses with polarized lenses and 100% UV400 protection.",
    price: 4500,
    category: "sunglasses",
  },
  {
    id: "2",
    name: "Noise Cancelling Wireless Headphones - Black",
    description: "Over-ear wireless headphones with active noise cancellation and premium sound quality.",
    price: 17500,
    category: "electronics",
  },
  {
    id: "3",
    name: "Ergonomic Leather Office Chair with Lumbar Support",
    description: "Comfortable adjustable leather office chair featuring lumbar support for long working hours.",
    price: 22000,
    category: "furniture",
  },
  {
    id: "4",
    name: "4K Smart LED TV - 55 Inch with Voice Control",
    description: "Ultra HD Smart LED TV with built-in streaming apps, voice assistant, and 4K resolution.",
    price: 95000,
    category: "electronics",
  },
  {
    id: "5",
    name: "Blue Light Blocking Computer Glasses",
    description: "Protective blue light filtering glasses designed for long screen time and digital eye strain.",
    price: 2500,
    category: "glasses",
  },
  {
    id: "6",
    name: "Men's Denim Jacket - Classic Blue Slim Fit",
    description: "Trendy slim-fit blue denim jacket for casual outings, crafted from premium fabric.",
    price: 4800,
    category: "fashion",
  },
  {
    id: "7",
    name: "Premium Oak Wood Dining Table - 6 Seater",
    description: "Elegant oak wood dining table with a seating capacity for six people.",
    price: 85000,
    category: "furniture",
  },
  {
    id: "8",
    name: "Decorative Round Wall Mirror with Gold Frame",
    description: "Modern round wall mirror with a golden metal frame, perfect for contemporary decor.",
    price: 7800,
    category: "decor",
  },
  {
    id: "9",
    name: "Professional Kitchen Knife Set - Stainless Steel",
    description: "High-quality kitchen knife set with ergonomic handles and sharp stainless steel blades.",
    price: 4500,
    category: "kitchen",
  },
  {
    id: "10",
    name: "Luxury Cotton Bedsheet Set with Pillow Covers",
    description: "Soft, premium cotton bedsheet set including matching pillow covers for king-sized beds.",
    price: 6200,
    category: "home",
  },
  {
    id: "11",
    name: "Smart LED Desk Lamp with USB Charging",
    description: "Adjustable LED desk lamp featuring touch controls and built-in USB charging port.",
    price: 3500,
    category: "electronics",
  },
  {
    id: "12",
    name: "Men's Aviator Sunglasses with UV Protection",
    description: "Classic aviator sunglasses with polarized lenses and a metal frame for a stylish look.",
    price: 3800,
    category: "sunglasses",
  },
  {
    id: "13",
    name: "Women's Suede Crossbody Handbag",
    description: "Elegant suede handbag with adjustable strap and spacious interior compartments.",
    price: 6200,
    category: "fashion",
  },
  {
    id: "14",
    name: "Compact Wooden Bookshelf Organizer - 5 Tier",
    description: "Space-saving wooden bookshelf with five open shelves for storage and display.",
    price: 8500,
    category: "furniture",
  },
  {
    id: "15",
    name: "UV Protection Sports Sunglasses with Polarized Lenses",
    description: "Lightweight sports sunglasses designed with anti-slip grip, polarized lenses, and UV400 protection.",
    price: 2900,
    category: "sunglasses",
  },
  {
    id: "16",
    name: "Stainless Steel Insulated Water Bottle - 1 Liter",
    description: "Double-wall vacuum insulated water bottle keeps beverages hot or cold for hours.",
    price: 2200,
    category: "kitchen",
  },
  {
    id: "17",
    name: "Portable Bluetooth Speaker with Deep Bass",
    description: "Compact wireless Bluetooth speaker delivering powerful bass and 10-hour playtime.",
    price: 5600,
    category: "electronics",
  },
  {
    id: "18",
    name: "Digital Smartwatch with Fitness Tracker",
    description: "Waterproof smartwatch featuring heart rate monitor, fitness tracking, and message notifications.",
    price: 8900,
    category: "electronics",
  },
  {
    id: "19",
    name: "High-Back Gaming Chair with Adjustable Armrests",
    description: "Ergonomic gaming chair with recline function, lumbar support, and high-density foam padding.",
    price: 28500,
    category: "furniture",
  },
  {
    id: "20",
    name: "LED String Lights for Home Decor",
    description: "Warm white LED string lights perfect for indoor decoration and festive occasions.",
    price: 1500,
    category: "decor",
  },
  {
    id: "21",
    name: "Men's Leather Wallet with RFID Blocking",
    description: "Premium leather wallet equipped with RFID blocking technology for secure transactions.",
    price: 3200,
    category: "fashion",
  },
  {
    id: "22",
    name: "Professional Hair Dryer with Ionic Technology",
    description: "Salon-grade hair dryer with fast drying and advanced ionic conditioning features.",
    price: 4800,
    category: "electronics",
  },
  {
    id: "23",
    name: "Non-Stick Cookware Set - 5 Pieces",
    description: "Durable non-stick cookware set including frying pans and saucepans with lids.",
    price: 11500,
    category: "kitchen",
  },
  {
    id: "24",
    name: "Cotton Bath Towel Set - Pack of 3",
    description: "Super absorbent cotton bath towels, soft and durable for everyday use.",
    price: 3900,
    category: "home",
  },
  {
    id: "25",
    name: "Men's Running Shoes - Lightweight & Breathable",
    description: "Comfortable running shoes with breathable mesh upper and cushioned sole.",
    price: 7200,
    category: "fashion",
  },
  {
    id: "26",
    name: "Wireless Keyboard and Mouse Combo",
    description: "Compact wireless keyboard and mouse combo with long battery life and ergonomic design.",
    price: 4600,
    category: "electronics",
  },
  {
    id: "27",
    name: "Wall Mounted Floating Shelves - Set of 3",
    description: "Modern floating shelves for wall mounting, ideal for storage and decoration.",
    price: 5200,
    category: "decor",
  },
  {
    id: "28",
    name: "Ceramic Dinnerware Set - 16 Pieces",
    description: "Elegant ceramic dinnerware set including dinner plates, bowls, and mugs.",
    price: 14500,
    category: "kitchen",
  },
  {
    id: "29",
    name: "Memory Foam Pillow for Neck Support",
    description: "Ergonomic memory foam pillow designed for maximum neck and shoulder support.",
    price: 6800,
    category: "home",
  },
  {
    id: "30",
    name: "Men's Polarized Clip-On Sunglasses for Prescription Glasses",
    description: "Convenient polarized clip-on sunglasses suitable for most prescription eyewear.",
    price: 1600,
    category: "glasses",
  },
];
